# Generated by Django 5.0.6 on 2024-07-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.sector')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_return', models.FloatField()),
                ('cumulative_return', models.FloatField()),
                ('sma_50', models.FloatField()),
                ('sma_200', models.FloatField()),
                ('rsi', models.FloatField()),
                ('upper_bb', models.FloatField()),
                ('lower_bb', models.FloatField()),
                ('obv', models.FloatField()),
                ('force_index', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('final_decision', models.CharField(max_length=10)),
                ('market_condition', models.CharField(max_length=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
