# Generated by Django 5.0.6 on 2024-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_sector_stock_stockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
