# Generated by Django 5.0.6 on 2024-07-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
